### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by ohyeah521** [felix-fly/v2ray-dnsmasq-dnscrypt#12]
-

**Comment by felix-fly** [comment]
感谢反馈，对v2ray的操作并不会影响ipset，dnsmasq和iptables才会影响。导出导入性价比不高，如果遇到这种情况清空电脑dns缓存即可，操作更简单。

**Comment by ohyeah521** [comment]
> 感谢反馈，对v2ray的操作并不会影响ipset，dnsmasq和iptables才会影响。导出导入性价比不高，如果遇到这种情况清空电脑dns缓存即可，操作更简单。

电脑还能清理，移动设备比较麻烦，每次都要开飞行模式，最关键的是修改一次，全家的设备都要搞，有点麻烦

**Comment by felix-fly** [comment]
可能你的设备多有这个需求，个人使用中还没有遇到你这种场景。还是很感谢你的建议，后期如果有需要会加到文章描述中。

**Comment by ohyeah521** [comment]
是的，手机，平板啥的，周末用的时候发现这个问题，后来复测了几次才找到原因，本地电脑缓存了ip，但是ipset的list为空，导致不能走代理

**Comment by ohyeah521** [comment]
刚刚突然想到一个新的解决方案，重启服务或修改了配置以后主动调用一个函数，该函数负责ping一下gfwlist中的域名即可，也不用备份和导入了
