### ISSUE TITLE
无法找到 gw.ips

### ISSUE THREAD

**Issue by tbs575** [felix-fly/v2ray-dnsmasq-dnscrypt#19]
我直接下载ZIP包，手动配置。在 `(1) v2ray开另外一个端口（推荐）`步骤中，提到了 `ipset -R < /etc/config/v2ray/gw.ips` ，在repo中没发现 gw.ips 文件。请问这个文件什么地方能找到呢？谢谢

**Comment by felix-fly** [comment]
现在把 *.ips 去掉了，防火墙规则漏掉了，我改过了，可以重新下一份用
