### ISSUE TITLE
很惨配置不成功

### ISSUE THREAD

**Issue by SenLief** [felix-fly/v2ray-dnsmasq-dnscrypt#8]
配置不成功，主要还不知道那一步有问题，这个DOH是只有一个配置文件就行了吗，还是要运行什么app

**Comment by felix-fly** [comment]
把文档重新整理了下，你试试看

**Comment by SenLief** [comment]
> 把文档重新整理了下，你试试看

https-dns-proxy有k2p的ipk吗？我找了几个都无法安装提示平台不对。

**Comment by felix-fly** [comment]
没有，不仅和平台有关，有些ipk和内核版本也有关。

**Comment by SenLief** [comment]
比较惨的是我用v2ray新开端口的一个方案也无法解析。一直解析不到IP。https那个我看官网说是opkg可以但是我安装提示没有这个包。

**Comment by felix-fly** [comment]
ssh路由执行一下防火墙规则看有没有报错 也可以电脑上用dig命令查询域名看是否正常

**Comment by SenLief** [comment]
我这边用dnsmasq -test返回错误，不知道是不是和这个有关系
dnsmasq: failed to create listening socket for port 53: Address already in use

**Comment by felix-fly** [comment]
这个错不影响，是因为dnsmasq本来就运行着

**Comment by SenLief** [comment]
还是不行，正常的网站是没有问题的，但是打开墙的网站应该是没有走代理，因为我开debug看不到任何走代理的信息。应该是没有代理才对。

**Comment by SenLief** [comment]
我感觉是不是gw透明代理规则有问题，可以看到v2ray监听了tcp12345端口和udp 1053端口但是好像没有转发过来。

**Comment by felix-fly** [comment]
是的 所以才要直接执行防火墙规则看报什么错

**Comment by SenLief** [comment]
防火墙规则报错的是Ipset的报错，提示已经有了该条目了，下面两行都没有报错。

**Comment by felix-fly** [comment]
最后那条规则整理的时候弄错了不是OUTPUT而是PREROUTING

**Comment by SenLief** [comment]
还是不行，这样无法解析，应该是所有在gw表里面的都没有解析，或者说gw表中的没有转给v2ray处理。

**Comment by SenLief** [comment]
OK了，重启重新调试一下就OK了。多谢哈。
