### ISSUE TITLE
DOH在潘多拉上无法安装

### ISSUE THREAD

**Issue by SenLief** [felix-fly/v2ray-dnsmasq-dnscrypt#9]
v2ray的方法通过了，但是doh应该在k2p的潘多拉固件上无法安装，https-dns-proxy依赖的libcurl4但是默认的包里面只有libcurl，版本等级不够，应该是无法运行，配置之后出错了。暂时应该没法搞定。

**Comment by felix-fly** [comment]
潘多拉内核是3系列的，对应的软件也是低版本的，想用的话需要自己编译https-dns-proxy

**Comment by SenLief** [comment]
怪不得呢，算了我打算直接安装openwrt算了。

**Comment by felix-fly** [comment]
潘多拉就用v2ray解析域名这种就好了啊 简单也好用

**Comment by SenLief** [comment]
嗯 现在就用这个v2ray的模式，还好吧，能用。就是配置总是要来回的更换。问题不大，以后有机会自己编译一下openwrt好了。
